name: Docker

"on":
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-epp:
    uses: docker/github-builder/.github/workflows/build.yml@v1
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    with:
      file: Dockerfile.epp
      context: .
      output: image
      platforms: linux/amd64,linux/arm64
      push: true
      cache: true
      cache-mode: max
      build-args: |
        COMMIT_SHA=${{ github.sha }}
        BUILD_REF=${{ github.ref_name }}
        LDFLAGS=-s -w
      meta-images: ghcr.io/${{ github.repository }}
      meta-tags: |
        type=ref,event=branch
        type=ref,event=tag
        type=semver,pattern={{version}}
        type=semver,pattern={{major}}.{{minor}}
        type=sha,format=short
        type=raw,value=latest,enable={{is_default_branch}}
    secrets:
      registry-auths: |
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
